development:
  adapter: postgresql
  encoding: unicode
  database: koerahoidja_development
  pool: 5
  host: localhost
  username: koerahoidja
  password: wL2EM668

test:
  adapter: postgresql
  encoding: unicode
  database: koerahoidja_test
  pool: 5
  host: localhost
  username: koerahoidja
  password: wL2EM668

production:
  adapter: postgresql
  database: koerahoidja_production
  pool: 5
  host: localhost
  timeout: 5000
  username: koerahoidja
  password: wL2EM668

